M48
; DRILL file {KiCad 7.0.10} date Sat Feb 24 17:37:46 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-24T17:37:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X105.605Y-102.71
X105.605Y-108.49
T2
X105.8Y-89.4
X110.88Y-81.78
M30
